name: Upload coverage reports to Codecov

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install -o Acquire::Retries=3 lcov
      
    - name: Configure CMake    
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_COVERAGE_INFO=true

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ./bdig_tests

    - name: Coverage
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target coverage
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        verbose: true
        fail_ci_if_error: true
        
    - name: Upload coverage reports to Codasy
      env:
         CODECOV_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}      
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
